src/objects/Basket__c.object
<CustomObject>
    <label>Basket</label>
    <nameField>
        <displayFormat>A-{0}</displayFormat>
        <label>Basket Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Baskets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Item__c.object
<CustomObject>
    <fields>
        <fullName>Count__c</fullName>
        <label>Count</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/JunctionBasket__c.object
<CustomObject>
    <fields>
        <fullName>BasketReference__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BasketReference</label>
        <referenceTo>Basket__c</referenceTo>
        <relationshipLabel>JunctionBaskets</relationshipLabel>
        <relationshipName>JunctionBaskets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ItemCount__c</fullName>
        <label>ItemCount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ItemReference__c</fullName>
        <label>ItemReference</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>JunctionBaskets</relationshipLabel>
        <relationshipName>JunctionBaskets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>JunctionBasket</label>
    <nameField>
        <displayFormat>A-{0}</displayFormat>
        <label>JunctionBasket Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>JunctionBaskets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BackUp.cls
public with sharing class BackUp {

    private String basketList = Label.listBaskets;


    public Basket__c basket { get; set; }
    public Set<ID> itemsListIds = new Set<ID>();
    public List<Item__c> items { get; set; }

    public List<JunctionBasket__c> junctionBasketsForView{get;set;}


    public List<JunctionBasket__c> junctionBaskets { get; set; }
    public BackUp(ApexPages.StandardController controller) {

        basket = [
                SELECT id
                FROM Basket__c
                WHERE id = :ApexPages.currentPage().getParameters().get('id')
        ];

        junctionBaskets = [
                SELECT BasketReference__c,ItemReference__c, ItemCount__c
                FROM JunctionBasket__c
                WHERE BasketReference__c = :basket.id
        ];
        getListItems();
        items = [
                SELECT Count__c, id, Name__c
                FROM Item__c
                WHERE id IN:itemsListIds
        ];
        junctionBasketsForView=[
                SELECT id,
                        ItemReference__r.Name__c,
                        ItemReference__r.Price__c,
                        ItemCount__c
                FROM JunctionBasket__c
                WHERE BasketReference__c =:ApexPages.currentPage().getParameters().get('id')
        ];

    }


    private void getListItems() {
        for (JunctionBasket__c junctionBasket : junctionBaskets) {
            itemsListIds.add(junctionBasket.ItemReference__c);
        }
    }

    private void returenCountInItems() {
        for (Item__c item : items) {
            for (JunctionBasket__c junctionBasket : junctionBaskets) {
                if (junctionBasket.ItemReference__c == item.id) {
                    item.Count__c = item.Count__c + junctionBasket.ItemCount__c;
                }
            }
        }
        upsert items;
    }


    public PageReference backUp() {
        returenCountInItems();
        delete basket;
        return new PageReference(basketList);

    }

}