src/objects/Category__c.object
<CustomObject>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Item__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Category</label>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Count__c</fullName>
        <label>Count</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CategoryController.cls
public with sharing class CategoryController{
    public List<Item__c> items {get;set;}

    public CategoryController(ApexPages.StandardSetController controller){
        items = [
                SELECT Id, Name, Price__c, Category__c, Count__c
                FROM Item__c
                WHERE Category__c =: ApexPages.currentPage().getParameters().get('id')
        ];

    }

    public void showItems(){

        items = [SELECT Id, Name, Price__c, Category__c, Count__c
                FROM Item__c
                WHERE Category__c =: ApexPages.currentPage().getParameters().get('id')
        ];
    }

    public List<Item__c> getItems(){
        return items;
    }


}