src/objects/Item__c.object
<CustomObject>
    <fields>
        <fullName>Count__c</fullName>
        <label>Count</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ItemHandler.cls
public with sharing class ItemHandler {

    public static void checkUddateOrInsert(List<Item__c> items) {
        /**
        Get All List Items from Database
         */
        List<Item__c> allListTerrs = [
                SELECT id, name, Count__c
                FROM Item__c
        ];

        /**
        Checking count on every items and Increases the if less than 3
         */
        for(Integer i = 0 ; i< items.size();i++){
            if(items.get(i).Count__c < 3)
                items.get(i).Count__c = 7;
        }
    }

}